### PR TITLE
Remove casatools.sm from write_to_ms

### LINKED ISSUE #3: Remove CASA Simulation Code
The write_to_ms function in simulation.py makes use of the casatools simulator to construct the ms that Sirius uvw's and visibilities will be saved into. This should be changed to using only the dask-ms functionality. An example of how to construct a new ms with dask-ms can be found [here](https://github.com/ska-sa/dask-ms/blob/4c31ddd4806d90a7d11287f4377d4bad5ce2babf/daskms/tests/test_ms_creation.py). 

To simplify the graph that the dask scheduler must manage, compute() should be called twice: once to make all the subtables and another time to create the main table.

### PR DESCRIPTION
**Pull request by amcnicho**
Using the output of simple_simulation as a template (at least to start)
- [x] verify against expected output
  - [x] main table
  - [x] subtables
- [x] update documentation
- [x] test performance

This should resolve #3

### CODE REVIEW

**Comment by amcnicho** [comment]
As of no the MS generated by the dask-ms method on this branch has a main table that matches the one produced by the sm tool.

**Comment by amcnicho** [comment]
As of now the subtable creation routines are in a state that I would expect to produce identical output to the reference implementation, but instead `xds_to_table` is raising
```python
RuntimeError: Directory: output.ms/ANTENNA does not exist and cannot be created
``` 
The error is coming from `daskms.writes._create_table` via `casacore.tables.table._default_ms_subtable`. Still need to understand why that might be. Changing the order of the `dask.compute()` calls and table creation steps does not seem to affect this.

**Comment by amcnicho** [comment]
Output of the simple_simulation notebook now matches the reference implementation (apart from not having a SOURCE subtable). Using dask-ms for all the columns is about twice as fast as the old approach of sm tool + dask-ms for the main table.
```
Meta data creation  1.2502288818359375
reshape time  0.0014672279357910156
*** Dask compute time 40.84901404380798
compute and save time  40.84918689727783
```
vs.
```
*** Dask compute time (main table) 10.60988163948059
*** Dask compute time (subtables) 7.2459564208984375
*** Dask compute time (pointing table) 0.4772379398345947
```

**Review by Jan-Willem — COMMENTED** [review]
lgtm

**Pull request merged**
